project:
  type: book
  output-dir: docs
lang: en
lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: false

book:
  title: "PeaSulf 2025"
  subtitle: "Stay-green mutants in sulfur deficiency: the role of PsSULTR4"
  cover-image: src/f83dfd81918f-image-files.jpg
  favicon: src/ico/icon_pea_sulf.ico
  back-to-top-navigation: true
  author:
    - name: Corentin Maslard
      degrees: PhD
      email: maslard.corentin@gmail.com
      orcid: 0000-0002-6951-1963
      url: https://cmaslard.xyz
      affiliations: INRAE
      attributes:
        corresponding: true
  date: today
  date-format: long
  abstract: Under prolonged sulfur deficiency (–S), sultr4 mutants display a stay-green phenotype in vegetative leaves, suggesting that vacuolar sulfate availability may influence the progression of leaf senescence and nutrient remobilization. To investigate this phenomenon, we first examined nitrogen partitioning at maturity in wild-type and sultr4 plants grown under –S. We then focused on comparing leaf responses between sultr4 and wild-type genotypes under both –S and +S conditions, monitoring chlorophyll content throughout the reproductive period, examining transcriptional regulations at key reproductive stages when nutrients are actively remobilized, and quantifying sulfate as well as a range of metabolites, including amino acids. Our findings reveal that the stay-green phenotype in sultr4 mutants under –S consistently appears in multiple experiments, indicating a direct or indirect role for vacuolar sulfate in leaf senescence. Transcriptomic analyses show that sultr4 mutants exhibit patterns distinct from the conventional sulfur deficiency response, particularly regarding the regulation of chlorophyll degradation and leaf senescence. Autophagy and photosynthetic processes remain unaffected, but the inhibition of chlorophyll catabolism and the suppression of senescence-promoting pathways characterize the mutant phenotype. Metabolic profiling further indicates that vacuolar sulfate remobilization is pivotal for maintaining cysteine levels and balancing amino acids associated with aspartate metabolism under –S. Notably, the E568K mutant accumulates OAS early in the reproductive period, representing a precocious sulfur-starvation response dependent on SULTR4, in contrast to the W78* mutant. Overall, these results underscore the crucial function of vacuolar sulfate in modulating senescence and ensuring metabolic homeostasis during sulfur-limited conditions.
  chapters:
    - index.qmd
    #- report/intro/To-Do.qmd
    - references.qmd
  search:
    type: overlay
  repo-url: https://github.com/cmaslard/PeaSulf_2025/
  repo-actions: [source, issue]
  downloads: [pdf]
  sharing: [twitter, facebook, linkedin]
  output-file: the_book_pdf
  sidebar: 
    border: true
    logo: src/ico/icon_pea_sulf.ico
    collapse-level: 1
  page-footer: 
    border: true
    background: light
    left: 
      - icon: badge-cc-fill
        url: https://creativecommons.org/licenses/by-nc-sa/4.0/
      - text: "Corentin Maslard 2024"
        href: "https://cmaslard.xyz/" 
      
    center:
      - text: "{{< iconify fa6-solid:envelope >}}"
        href: "mailto:maslard.corentin@gmail.com"
        aria-label: "envelope logo for email"
      - text: "{{< iconify fa6-brands:github >}}"
      - icon: github
        href: https://github.com/cmaslard/phd_soybean_2021_2024/
      - text: "{{< iconify fa6-brands:linkedin >}}"
        href: https://www.linkedin.com/in/corentin-maslard
      - text: "{{< iconify fa6-brands square-x-twitter >}}"
        href: https://x.com/cmaslard
      - text: "{{< iconify fa6-brands:orcid >}}"
        href: "https://orcid.org/0000-0002-6951-1963"
        aria-label: "ORCID logo linking to ORCID account"
      - text: "{{< iconify fa6-brands:researchgate >}}"
        href: "https://www.researchgate.net/profile/Corentin-Maslard"
        aria-label: "ResearchGate logo linking to ResearchGate account"
      - text: "{{< iconify academicons:google-scholar >}}"
        href: https://scholar.google.com/citations?user=TsztyiMAAAAJ&hl
        target: blank
      - text: "{{< iconify academicons:hal >}}"
        href: https://cv.hal.science/corentinmaslard
        aria-label: "HAL account"
      - text: "{{< iconify pepicons-pop:cv >}}"
        href: "https://docs.google.com/document/d/1oCgrdjnAJuVjgocx3F2kmlbJxlqa6uWrSgqm5fWRhpA/edit?usp=sharing"
        aria-label: "CV"
    right:
        <span class="faux-block">Made with <iconify-icon icon="line-md:heart-twotone"></iconify-icon>, <iconify-icon icon="line-md:coffee-twotone-loop"></iconify-icon>, {{< iconify fa6-brands r-project >}} and [Quarto](https://quarto.org/)</span> |
        <span class="faux-block">[View the source at {{< iconify fa6-brands github >}} GitHub](https://github.com/cmaslard/cmaslard.github.io)</span>
      

bibliography: [references.bib]

format:
  html:
    grid:
      body-width: 1000px
    code-fold: true
    code-tools: true
    theme: 
      light: [cosmo, src/theme-light.scss]
      dark: [cosmo, src/theme-dark.scss]
    execute:
      echo: true
      warning: false
editor: source
